/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedRagIndexRouteImport } from './routes/_authenticated/rag.index'
import { Route as AuthenticatedPromptsIndexRouteImport } from './routes/_authenticated/prompts.index'
import { Route as AuthenticatedModelCardsIndexRouteImport } from './routes/_authenticated/model-cards.index'
import { Route as AuthenticatedFinetuneIndexRouteImport } from './routes/_authenticated/finetune.index'
import { Route as AuthenticatedExperimentsIndexRouteImport } from './routes/_authenticated/experiments.index'
import { Route as AuthenticatedEmbeddingsIndexRouteImport } from './routes/_authenticated/embeddings.index'
import { Route as AuthenticatedDatasetsIndexRouteImport } from './routes/_authenticated/datasets.index'
import { Route as AuthenticatedCostsIndexRouteImport } from './routes/_authenticated/costs.index'
import { Route as AuthenticatedChunkingIndexRouteImport } from './routes/_authenticated/chunking.index'
import { Route as AuthenticatedBenchmarksIndexRouteImport } from './routes/_authenticated/benchmarks.index'
import { Route as AuthenticatedAuditReportsIndexRouteImport } from './routes/_authenticated/audit-reports.index'
import { Route as ShareBenchmarksTokenRouteImport } from './routes/share.benchmarks.$token'
import { Route as AuthenticatedRagNewRouteImport } from './routes/_authenticated/rag.new'
import { Route as AuthenticatedRagIdRouteImport } from './routes/_authenticated/rag.$id'
import { Route as AuthenticatedPromptsNewRouteImport } from './routes/_authenticated/prompts.new'
import { Route as AuthenticatedModelCardsNewRouteImport } from './routes/_authenticated/model-cards.new'
import { Route as AuthenticatedModelCardsIdRouteImport } from './routes/_authenticated/model-cards.$id'
import { Route as AuthenticatedFinetuneNewRouteImport } from './routes/_authenticated/finetune.new'
import { Route as AuthenticatedFinetuneIdRouteImport } from './routes/_authenticated/finetune.$id'
import { Route as AuthenticatedExperimentsNewRouteImport } from './routes/_authenticated/experiments.new'
import { Route as AuthenticatedExperimentsIdRouteImport } from './routes/_authenticated/experiments.$id'
import { Route as AuthenticatedEmbeddingsNewRouteImport } from './routes/_authenticated/embeddings.new'
import { Route as AuthenticatedEmbeddingsIdRouteImport } from './routes/_authenticated/embeddings.$id'
import { Route as AuthenticatedDatasetsNewRouteImport } from './routes/_authenticated/datasets.new'
import { Route as AuthenticatedDatasetsIdRouteImport } from './routes/_authenticated/datasets.$id'
import { Route as AuthenticatedCostsNewRouteImport } from './routes/_authenticated/costs.new'
import { Route as AuthenticatedCostsIdRouteImport } from './routes/_authenticated/costs.$id'
import { Route as AuthenticatedChunkingNewRouteImport } from './routes/_authenticated/chunking.new'
import { Route as AuthenticatedChunkingIdRouteImport } from './routes/_authenticated/chunking.$id'
import { Route as AuthenticatedBenchmarksNewRouteImport } from './routes/_authenticated/benchmarks.new'
import { Route as AuthenticatedAuditReportsNewRouteImport } from './routes/_authenticated/audit-reports.new'
import { Route as AuthenticatedAuditReportsIdRouteImport } from './routes/_authenticated/audit-reports.$id'
import { Route as AuthenticatedPromptsIdIndexRouteImport } from './routes/_authenticated/prompts.$id.index'
import { Route as AuthenticatedBenchmarksIdIndexRouteImport } from './routes/_authenticated/benchmarks.$id.index'
import { Route as AuthenticatedPromptsIdRunsRunIdRouteImport } from './routes/_authenticated/prompts.$id.runs.$runId'
import { Route as AuthenticatedBenchmarksIdRunsRunIdRouteImport } from './routes/_authenticated/benchmarks.$id.runs.$runId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRagIndexRoute = AuthenticatedRagIndexRouteImport.update({
  id: '/rag/',
  path: '/rag/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsIndexRoute =
  AuthenticatedPromptsIndexRouteImport.update({
    id: '/prompts/',
    path: '/prompts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelCardsIndexRoute =
  AuthenticatedModelCardsIndexRouteImport.update({
    id: '/model-cards/',
    path: '/model-cards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinetuneIndexRoute =
  AuthenticatedFinetuneIndexRouteImport.update({
    id: '/finetune/',
    path: '/finetune/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperimentsIndexRoute =
  AuthenticatedExperimentsIndexRouteImport.update({
    id: '/experiments/',
    path: '/experiments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmbeddingsIndexRoute =
  AuthenticatedEmbeddingsIndexRouteImport.update({
    id: '/embeddings/',
    path: '/embeddings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsIndexRoute =
  AuthenticatedDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCostsIndexRoute = AuthenticatedCostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChunkingIndexRoute =
  AuthenticatedChunkingIndexRouteImport.update({
    id: '/chunking/',
    path: '/chunking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBenchmarksIndexRoute =
  AuthenticatedBenchmarksIndexRouteImport.update({
    id: '/benchmarks/',
    path: '/benchmarks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditReportsIndexRoute =
  AuthenticatedAuditReportsIndexRouteImport.update({
    id: '/audit-reports/',
    path: '/audit-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ShareBenchmarksTokenRoute = ShareBenchmarksTokenRouteImport.update({
  id: '/share/benchmarks/$token',
  path: '/share/benchmarks/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRagNewRoute = AuthenticatedRagNewRouteImport.update({
  id: '/rag/new',
  path: '/rag/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRagIdRoute = AuthenticatedRagIdRouteImport.update({
  id: '/rag/$id',
  path: '/rag/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsNewRoute = AuthenticatedPromptsNewRouteImport.update({
  id: '/prompts/new',
  path: '/prompts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelCardsNewRoute =
  AuthenticatedModelCardsNewRouteImport.update({
    id: '/model-cards/new',
    path: '/model-cards/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelCardsIdRoute =
  AuthenticatedModelCardsIdRouteImport.update({
    id: '/model-cards/$id',
    path: '/model-cards/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinetuneNewRoute =
  AuthenticatedFinetuneNewRouteImport.update({
    id: '/finetune/new',
    path: '/finetune/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinetuneIdRoute = AuthenticatedFinetuneIdRouteImport.update({
  id: '/finetune/$id',
  path: '/finetune/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsNewRoute =
  AuthenticatedExperimentsNewRouteImport.update({
    id: '/experiments/new',
    path: '/experiments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperimentsIdRoute =
  AuthenticatedExperimentsIdRouteImport.update({
    id: '/experiments/$id',
    path: '/experiments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmbeddingsNewRoute =
  AuthenticatedEmbeddingsNewRouteImport.update({
    id: '/embeddings/new',
    path: '/embeddings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmbeddingsIdRoute =
  AuthenticatedEmbeddingsIdRouteImport.update({
    id: '/embeddings/$id',
    path: '/embeddings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsNewRoute =
  AuthenticatedDatasetsNewRouteImport.update({
    id: '/datasets/new',
    path: '/datasets/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsIdRoute = AuthenticatedDatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsNewRoute = AuthenticatedCostsNewRouteImport.update({
  id: '/costs/new',
  path: '/costs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsIdRoute = AuthenticatedCostsIdRouteImport.update({
  id: '/costs/$id',
  path: '/costs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChunkingNewRoute =
  AuthenticatedChunkingNewRouteImport.update({
    id: '/chunking/new',
    path: '/chunking/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChunkingIdRoute = AuthenticatedChunkingIdRouteImport.update({
  id: '/chunking/$id',
  path: '/chunking/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenchmarksNewRoute =
  AuthenticatedBenchmarksNewRouteImport.update({
    id: '/benchmarks/new',
    path: '/benchmarks/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditReportsNewRoute =
  AuthenticatedAuditReportsNewRouteImport.update({
    id: '/audit-reports/new',
    path: '/audit-reports/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditReportsIdRoute =
  AuthenticatedAuditReportsIdRouteImport.update({
    id: '/audit-reports/$id',
    path: '/audit-reports/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromptsIdIndexRoute =
  AuthenticatedPromptsIdIndexRouteImport.update({
    id: '/prompts/$id/',
    path: '/prompts/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBenchmarksIdIndexRoute =
  AuthenticatedBenchmarksIdIndexRouteImport.update({
    id: '/benchmarks/$id/',
    path: '/benchmarks/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromptsIdRunsRunIdRoute =
  AuthenticatedPromptsIdRunsRunIdRouteImport.update({
    id: '/prompts/$id/runs/$runId',
    path: '/prompts/$id/runs/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBenchmarksIdRunsRunIdRoute =
  AuthenticatedBenchmarksIdRunsRunIdRouteImport.update({
    id: '/benchmarks/$id/runs/$runId',
    path: '/benchmarks/$id/runs/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audit-reports/$id': typeof AuthenticatedAuditReportsIdRoute
  '/audit-reports/new': typeof AuthenticatedAuditReportsNewRoute
  '/benchmarks/new': typeof AuthenticatedBenchmarksNewRoute
  '/chunking/$id': typeof AuthenticatedChunkingIdRoute
  '/chunking/new': typeof AuthenticatedChunkingNewRoute
  '/costs/$id': typeof AuthenticatedCostsIdRoute
  '/costs/new': typeof AuthenticatedCostsNewRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/datasets/new': typeof AuthenticatedDatasetsNewRoute
  '/embeddings/$id': typeof AuthenticatedEmbeddingsIdRoute
  '/embeddings/new': typeof AuthenticatedEmbeddingsNewRoute
  '/experiments/$id': typeof AuthenticatedExperimentsIdRoute
  '/experiments/new': typeof AuthenticatedExperimentsNewRoute
  '/finetune/$id': typeof AuthenticatedFinetuneIdRoute
  '/finetune/new': typeof AuthenticatedFinetuneNewRoute
  '/model-cards/$id': typeof AuthenticatedModelCardsIdRoute
  '/model-cards/new': typeof AuthenticatedModelCardsNewRoute
  '/prompts/new': typeof AuthenticatedPromptsNewRoute
  '/rag/$id': typeof AuthenticatedRagIdRoute
  '/rag/new': typeof AuthenticatedRagNewRoute
  '/share/benchmarks/$token': typeof ShareBenchmarksTokenRoute
  '/audit-reports/': typeof AuthenticatedAuditReportsIndexRoute
  '/benchmarks/': typeof AuthenticatedBenchmarksIndexRoute
  '/chunking/': typeof AuthenticatedChunkingIndexRoute
  '/costs/': typeof AuthenticatedCostsIndexRoute
  '/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/embeddings/': typeof AuthenticatedEmbeddingsIndexRoute
  '/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/finetune/': typeof AuthenticatedFinetuneIndexRoute
  '/model-cards/': typeof AuthenticatedModelCardsIndexRoute
  '/prompts/': typeof AuthenticatedPromptsIndexRoute
  '/rag/': typeof AuthenticatedRagIndexRoute
  '/benchmarks/$id/': typeof AuthenticatedBenchmarksIdIndexRoute
  '/prompts/$id/': typeof AuthenticatedPromptsIdIndexRoute
  '/benchmarks/$id/runs/$runId': typeof AuthenticatedBenchmarksIdRunsRunIdRoute
  '/prompts/$id/runs/$runId': typeof AuthenticatedPromptsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audit-reports/$id': typeof AuthenticatedAuditReportsIdRoute
  '/audit-reports/new': typeof AuthenticatedAuditReportsNewRoute
  '/benchmarks/new': typeof AuthenticatedBenchmarksNewRoute
  '/chunking/$id': typeof AuthenticatedChunkingIdRoute
  '/chunking/new': typeof AuthenticatedChunkingNewRoute
  '/costs/$id': typeof AuthenticatedCostsIdRoute
  '/costs/new': typeof AuthenticatedCostsNewRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/datasets/new': typeof AuthenticatedDatasetsNewRoute
  '/embeddings/$id': typeof AuthenticatedEmbeddingsIdRoute
  '/embeddings/new': typeof AuthenticatedEmbeddingsNewRoute
  '/experiments/$id': typeof AuthenticatedExperimentsIdRoute
  '/experiments/new': typeof AuthenticatedExperimentsNewRoute
  '/finetune/$id': typeof AuthenticatedFinetuneIdRoute
  '/finetune/new': typeof AuthenticatedFinetuneNewRoute
  '/model-cards/$id': typeof AuthenticatedModelCardsIdRoute
  '/model-cards/new': typeof AuthenticatedModelCardsNewRoute
  '/prompts/new': typeof AuthenticatedPromptsNewRoute
  '/rag/$id': typeof AuthenticatedRagIdRoute
  '/rag/new': typeof AuthenticatedRagNewRoute
  '/share/benchmarks/$token': typeof ShareBenchmarksTokenRoute
  '/audit-reports': typeof AuthenticatedAuditReportsIndexRoute
  '/benchmarks': typeof AuthenticatedBenchmarksIndexRoute
  '/chunking': typeof AuthenticatedChunkingIndexRoute
  '/costs': typeof AuthenticatedCostsIndexRoute
  '/datasets': typeof AuthenticatedDatasetsIndexRoute
  '/embeddings': typeof AuthenticatedEmbeddingsIndexRoute
  '/experiments': typeof AuthenticatedExperimentsIndexRoute
  '/finetune': typeof AuthenticatedFinetuneIndexRoute
  '/model-cards': typeof AuthenticatedModelCardsIndexRoute
  '/prompts': typeof AuthenticatedPromptsIndexRoute
  '/rag': typeof AuthenticatedRagIndexRoute
  '/benchmarks/$id': typeof AuthenticatedBenchmarksIdIndexRoute
  '/prompts/$id': typeof AuthenticatedPromptsIdIndexRoute
  '/benchmarks/$id/runs/$runId': typeof AuthenticatedBenchmarksIdRunsRunIdRoute
  '/prompts/$id/runs/$runId': typeof AuthenticatedPromptsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/audit-reports/$id': typeof AuthenticatedAuditReportsIdRoute
  '/_authenticated/audit-reports/new': typeof AuthenticatedAuditReportsNewRoute
  '/_authenticated/benchmarks/new': typeof AuthenticatedBenchmarksNewRoute
  '/_authenticated/chunking/$id': typeof AuthenticatedChunkingIdRoute
  '/_authenticated/chunking/new': typeof AuthenticatedChunkingNewRoute
  '/_authenticated/costs/$id': typeof AuthenticatedCostsIdRoute
  '/_authenticated/costs/new': typeof AuthenticatedCostsNewRoute
  '/_authenticated/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/_authenticated/datasets/new': typeof AuthenticatedDatasetsNewRoute
  '/_authenticated/embeddings/$id': typeof AuthenticatedEmbeddingsIdRoute
  '/_authenticated/embeddings/new': typeof AuthenticatedEmbeddingsNewRoute
  '/_authenticated/experiments/$id': typeof AuthenticatedExperimentsIdRoute
  '/_authenticated/experiments/new': typeof AuthenticatedExperimentsNewRoute
  '/_authenticated/finetune/$id': typeof AuthenticatedFinetuneIdRoute
  '/_authenticated/finetune/new': typeof AuthenticatedFinetuneNewRoute
  '/_authenticated/model-cards/$id': typeof AuthenticatedModelCardsIdRoute
  '/_authenticated/model-cards/new': typeof AuthenticatedModelCardsNewRoute
  '/_authenticated/prompts/new': typeof AuthenticatedPromptsNewRoute
  '/_authenticated/rag/$id': typeof AuthenticatedRagIdRoute
  '/_authenticated/rag/new': typeof AuthenticatedRagNewRoute
  '/share/benchmarks/$token': typeof ShareBenchmarksTokenRoute
  '/_authenticated/audit-reports/': typeof AuthenticatedAuditReportsIndexRoute
  '/_authenticated/benchmarks/': typeof AuthenticatedBenchmarksIndexRoute
  '/_authenticated/chunking/': typeof AuthenticatedChunkingIndexRoute
  '/_authenticated/costs/': typeof AuthenticatedCostsIndexRoute
  '/_authenticated/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/_authenticated/embeddings/': typeof AuthenticatedEmbeddingsIndexRoute
  '/_authenticated/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/_authenticated/finetune/': typeof AuthenticatedFinetuneIndexRoute
  '/_authenticated/model-cards/': typeof AuthenticatedModelCardsIndexRoute
  '/_authenticated/prompts/': typeof AuthenticatedPromptsIndexRoute
  '/_authenticated/rag/': typeof AuthenticatedRagIndexRoute
  '/_authenticated/benchmarks/$id/': typeof AuthenticatedBenchmarksIdIndexRoute
  '/_authenticated/prompts/$id/': typeof AuthenticatedPromptsIdIndexRoute
  '/_authenticated/benchmarks/$id/runs/$runId': typeof AuthenticatedBenchmarksIdRunsRunIdRoute
  '/_authenticated/prompts/$id/runs/$runId': typeof AuthenticatedPromptsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/audit-reports/$id'
    | '/audit-reports/new'
    | '/benchmarks/new'
    | '/chunking/$id'
    | '/chunking/new'
    | '/costs/$id'
    | '/costs/new'
    | '/datasets/$id'
    | '/datasets/new'
    | '/embeddings/$id'
    | '/embeddings/new'
    | '/experiments/$id'
    | '/experiments/new'
    | '/finetune/$id'
    | '/finetune/new'
    | '/model-cards/$id'
    | '/model-cards/new'
    | '/prompts/new'
    | '/rag/$id'
    | '/rag/new'
    | '/share/benchmarks/$token'
    | '/audit-reports/'
    | '/benchmarks/'
    | '/chunking/'
    | '/costs/'
    | '/datasets/'
    | '/embeddings/'
    | '/experiments/'
    | '/finetune/'
    | '/model-cards/'
    | '/prompts/'
    | '/rag/'
    | '/benchmarks/$id/'
    | '/prompts/$id/'
    | '/benchmarks/$id/runs/$runId'
    | '/prompts/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/audit-reports/$id'
    | '/audit-reports/new'
    | '/benchmarks/new'
    | '/chunking/$id'
    | '/chunking/new'
    | '/costs/$id'
    | '/costs/new'
    | '/datasets/$id'
    | '/datasets/new'
    | '/embeddings/$id'
    | '/embeddings/new'
    | '/experiments/$id'
    | '/experiments/new'
    | '/finetune/$id'
    | '/finetune/new'
    | '/model-cards/$id'
    | '/model-cards/new'
    | '/prompts/new'
    | '/rag/$id'
    | '/rag/new'
    | '/share/benchmarks/$token'
    | '/audit-reports'
    | '/benchmarks'
    | '/chunking'
    | '/costs'
    | '/datasets'
    | '/embeddings'
    | '/experiments'
    | '/finetune'
    | '/model-cards'
    | '/prompts'
    | '/rag'
    | '/benchmarks/$id'
    | '/prompts/$id'
    | '/benchmarks/$id/runs/$runId'
    | '/prompts/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/audit-reports/$id'
    | '/_authenticated/audit-reports/new'
    | '/_authenticated/benchmarks/new'
    | '/_authenticated/chunking/$id'
    | '/_authenticated/chunking/new'
    | '/_authenticated/costs/$id'
    | '/_authenticated/costs/new'
    | '/_authenticated/datasets/$id'
    | '/_authenticated/datasets/new'
    | '/_authenticated/embeddings/$id'
    | '/_authenticated/embeddings/new'
    | '/_authenticated/experiments/$id'
    | '/_authenticated/experiments/new'
    | '/_authenticated/finetune/$id'
    | '/_authenticated/finetune/new'
    | '/_authenticated/model-cards/$id'
    | '/_authenticated/model-cards/new'
    | '/_authenticated/prompts/new'
    | '/_authenticated/rag/$id'
    | '/_authenticated/rag/new'
    | '/share/benchmarks/$token'
    | '/_authenticated/audit-reports/'
    | '/_authenticated/benchmarks/'
    | '/_authenticated/chunking/'
    | '/_authenticated/costs/'
    | '/_authenticated/datasets/'
    | '/_authenticated/embeddings/'
    | '/_authenticated/experiments/'
    | '/_authenticated/finetune/'
    | '/_authenticated/model-cards/'
    | '/_authenticated/prompts/'
    | '/_authenticated/rag/'
    | '/_authenticated/benchmarks/$id/'
    | '/_authenticated/prompts/$id/'
    | '/_authenticated/benchmarks/$id/runs/$runId'
    | '/_authenticated/prompts/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareBenchmarksTokenRoute: typeof ShareBenchmarksTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rag/': {
      id: '/_authenticated/rag/'
      path: '/rag'
      fullPath: '/rag/'
      preLoaderRoute: typeof AuthenticatedRagIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts/': {
      id: '/_authenticated/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof AuthenticatedPromptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-cards/': {
      id: '/_authenticated/model-cards/'
      path: '/model-cards'
      fullPath: '/model-cards/'
      preLoaderRoute: typeof AuthenticatedModelCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finetune/': {
      id: '/_authenticated/finetune/'
      path: '/finetune'
      fullPath: '/finetune/'
      preLoaderRoute: typeof AuthenticatedFinetuneIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments/': {
      id: '/_authenticated/experiments/'
      path: '/experiments'
      fullPath: '/experiments/'
      preLoaderRoute: typeof AuthenticatedExperimentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/embeddings/': {
      id: '/_authenticated/embeddings/'
      path: '/embeddings'
      fullPath: '/embeddings/'
      preLoaderRoute: typeof AuthenticatedEmbeddingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/': {
      id: '/_authenticated/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AuthenticatedDatasetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs/': {
      id: '/_authenticated/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof AuthenticatedCostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chunking/': {
      id: '/_authenticated/chunking/'
      path: '/chunking'
      fullPath: '/chunking/'
      preLoaderRoute: typeof AuthenticatedChunkingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benchmarks/': {
      id: '/_authenticated/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof AuthenticatedBenchmarksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-reports/': {
      id: '/_authenticated/audit-reports/'
      path: '/audit-reports'
      fullPath: '/audit-reports/'
      preLoaderRoute: typeof AuthenticatedAuditReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/benchmarks/$token': {
      id: '/share/benchmarks/$token'
      path: '/share/benchmarks/$token'
      fullPath: '/share/benchmarks/$token'
      preLoaderRoute: typeof ShareBenchmarksTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rag/new': {
      id: '/_authenticated/rag/new'
      path: '/rag/new'
      fullPath: '/rag/new'
      preLoaderRoute: typeof AuthenticatedRagNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rag/$id': {
      id: '/_authenticated/rag/$id'
      path: '/rag/$id'
      fullPath: '/rag/$id'
      preLoaderRoute: typeof AuthenticatedRagIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts/new': {
      id: '/_authenticated/prompts/new'
      path: '/prompts/new'
      fullPath: '/prompts/new'
      preLoaderRoute: typeof AuthenticatedPromptsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-cards/new': {
      id: '/_authenticated/model-cards/new'
      path: '/model-cards/new'
      fullPath: '/model-cards/new'
      preLoaderRoute: typeof AuthenticatedModelCardsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-cards/$id': {
      id: '/_authenticated/model-cards/$id'
      path: '/model-cards/$id'
      fullPath: '/model-cards/$id'
      preLoaderRoute: typeof AuthenticatedModelCardsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finetune/new': {
      id: '/_authenticated/finetune/new'
      path: '/finetune/new'
      fullPath: '/finetune/new'
      preLoaderRoute: typeof AuthenticatedFinetuneNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finetune/$id': {
      id: '/_authenticated/finetune/$id'
      path: '/finetune/$id'
      fullPath: '/finetune/$id'
      preLoaderRoute: typeof AuthenticatedFinetuneIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments/new': {
      id: '/_authenticated/experiments/new'
      path: '/experiments/new'
      fullPath: '/experiments/new'
      preLoaderRoute: typeof AuthenticatedExperimentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments/$id': {
      id: '/_authenticated/experiments/$id'
      path: '/experiments/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof AuthenticatedExperimentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/embeddings/new': {
      id: '/_authenticated/embeddings/new'
      path: '/embeddings/new'
      fullPath: '/embeddings/new'
      preLoaderRoute: typeof AuthenticatedEmbeddingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/embeddings/$id': {
      id: '/_authenticated/embeddings/$id'
      path: '/embeddings/$id'
      fullPath: '/embeddings/$id'
      preLoaderRoute: typeof AuthenticatedEmbeddingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/new': {
      id: '/_authenticated/datasets/new'
      path: '/datasets/new'
      fullPath: '/datasets/new'
      preLoaderRoute: typeof AuthenticatedDatasetsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/$id': {
      id: '/_authenticated/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof AuthenticatedDatasetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs/new': {
      id: '/_authenticated/costs/new'
      path: '/costs/new'
      fullPath: '/costs/new'
      preLoaderRoute: typeof AuthenticatedCostsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs/$id': {
      id: '/_authenticated/costs/$id'
      path: '/costs/$id'
      fullPath: '/costs/$id'
      preLoaderRoute: typeof AuthenticatedCostsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chunking/new': {
      id: '/_authenticated/chunking/new'
      path: '/chunking/new'
      fullPath: '/chunking/new'
      preLoaderRoute: typeof AuthenticatedChunkingNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chunking/$id': {
      id: '/_authenticated/chunking/$id'
      path: '/chunking/$id'
      fullPath: '/chunking/$id'
      preLoaderRoute: typeof AuthenticatedChunkingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benchmarks/new': {
      id: '/_authenticated/benchmarks/new'
      path: '/benchmarks/new'
      fullPath: '/benchmarks/new'
      preLoaderRoute: typeof AuthenticatedBenchmarksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-reports/new': {
      id: '/_authenticated/audit-reports/new'
      path: '/audit-reports/new'
      fullPath: '/audit-reports/new'
      preLoaderRoute: typeof AuthenticatedAuditReportsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-reports/$id': {
      id: '/_authenticated/audit-reports/$id'
      path: '/audit-reports/$id'
      fullPath: '/audit-reports/$id'
      preLoaderRoute: typeof AuthenticatedAuditReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts/$id/': {
      id: '/_authenticated/prompts/$id/'
      path: '/prompts/$id'
      fullPath: '/prompts/$id/'
      preLoaderRoute: typeof AuthenticatedPromptsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benchmarks/$id/': {
      id: '/_authenticated/benchmarks/$id/'
      path: '/benchmarks/$id'
      fullPath: '/benchmarks/$id/'
      preLoaderRoute: typeof AuthenticatedBenchmarksIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts/$id/runs/$runId': {
      id: '/_authenticated/prompts/$id/runs/$runId'
      path: '/prompts/$id/runs/$runId'
      fullPath: '/prompts/$id/runs/$runId'
      preLoaderRoute: typeof AuthenticatedPromptsIdRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benchmarks/$id/runs/$runId': {
      id: '/_authenticated/benchmarks/$id/runs/$runId'
      path: '/benchmarks/$id/runs/$runId'
      fullPath: '/benchmarks/$id/runs/$runId'
      preLoaderRoute: typeof AuthenticatedBenchmarksIdRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAuditReportsIdRoute: typeof AuthenticatedAuditReportsIdRoute
  AuthenticatedAuditReportsNewRoute: typeof AuthenticatedAuditReportsNewRoute
  AuthenticatedBenchmarksNewRoute: typeof AuthenticatedBenchmarksNewRoute
  AuthenticatedChunkingIdRoute: typeof AuthenticatedChunkingIdRoute
  AuthenticatedChunkingNewRoute: typeof AuthenticatedChunkingNewRoute
  AuthenticatedCostsIdRoute: typeof AuthenticatedCostsIdRoute
  AuthenticatedCostsNewRoute: typeof AuthenticatedCostsNewRoute
  AuthenticatedDatasetsIdRoute: typeof AuthenticatedDatasetsIdRoute
  AuthenticatedDatasetsNewRoute: typeof AuthenticatedDatasetsNewRoute
  AuthenticatedEmbeddingsIdRoute: typeof AuthenticatedEmbeddingsIdRoute
  AuthenticatedEmbeddingsNewRoute: typeof AuthenticatedEmbeddingsNewRoute
  AuthenticatedExperimentsIdRoute: typeof AuthenticatedExperimentsIdRoute
  AuthenticatedExperimentsNewRoute: typeof AuthenticatedExperimentsNewRoute
  AuthenticatedFinetuneIdRoute: typeof AuthenticatedFinetuneIdRoute
  AuthenticatedFinetuneNewRoute: typeof AuthenticatedFinetuneNewRoute
  AuthenticatedModelCardsIdRoute: typeof AuthenticatedModelCardsIdRoute
  AuthenticatedModelCardsNewRoute: typeof AuthenticatedModelCardsNewRoute
  AuthenticatedPromptsNewRoute: typeof AuthenticatedPromptsNewRoute
  AuthenticatedRagIdRoute: typeof AuthenticatedRagIdRoute
  AuthenticatedRagNewRoute: typeof AuthenticatedRagNewRoute
  AuthenticatedAuditReportsIndexRoute: typeof AuthenticatedAuditReportsIndexRoute
  AuthenticatedBenchmarksIndexRoute: typeof AuthenticatedBenchmarksIndexRoute
  AuthenticatedChunkingIndexRoute: typeof AuthenticatedChunkingIndexRoute
  AuthenticatedCostsIndexRoute: typeof AuthenticatedCostsIndexRoute
  AuthenticatedDatasetsIndexRoute: typeof AuthenticatedDatasetsIndexRoute
  AuthenticatedEmbeddingsIndexRoute: typeof AuthenticatedEmbeddingsIndexRoute
  AuthenticatedExperimentsIndexRoute: typeof AuthenticatedExperimentsIndexRoute
  AuthenticatedFinetuneIndexRoute: typeof AuthenticatedFinetuneIndexRoute
  AuthenticatedModelCardsIndexRoute: typeof AuthenticatedModelCardsIndexRoute
  AuthenticatedPromptsIndexRoute: typeof AuthenticatedPromptsIndexRoute
  AuthenticatedRagIndexRoute: typeof AuthenticatedRagIndexRoute
  AuthenticatedBenchmarksIdIndexRoute: typeof AuthenticatedBenchmarksIdIndexRoute
  AuthenticatedPromptsIdIndexRoute: typeof AuthenticatedPromptsIdIndexRoute
  AuthenticatedBenchmarksIdRunsRunIdRoute: typeof AuthenticatedBenchmarksIdRunsRunIdRoute
  AuthenticatedPromptsIdRunsRunIdRoute: typeof AuthenticatedPromptsIdRunsRunIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAuditReportsIdRoute: AuthenticatedAuditReportsIdRoute,
  AuthenticatedAuditReportsNewRoute: AuthenticatedAuditReportsNewRoute,
  AuthenticatedBenchmarksNewRoute: AuthenticatedBenchmarksNewRoute,
  AuthenticatedChunkingIdRoute: AuthenticatedChunkingIdRoute,
  AuthenticatedChunkingNewRoute: AuthenticatedChunkingNewRoute,
  AuthenticatedCostsIdRoute: AuthenticatedCostsIdRoute,
  AuthenticatedCostsNewRoute: AuthenticatedCostsNewRoute,
  AuthenticatedDatasetsIdRoute: AuthenticatedDatasetsIdRoute,
  AuthenticatedDatasetsNewRoute: AuthenticatedDatasetsNewRoute,
  AuthenticatedEmbeddingsIdRoute: AuthenticatedEmbeddingsIdRoute,
  AuthenticatedEmbeddingsNewRoute: AuthenticatedEmbeddingsNewRoute,
  AuthenticatedExperimentsIdRoute: AuthenticatedExperimentsIdRoute,
  AuthenticatedExperimentsNewRoute: AuthenticatedExperimentsNewRoute,
  AuthenticatedFinetuneIdRoute: AuthenticatedFinetuneIdRoute,
  AuthenticatedFinetuneNewRoute: AuthenticatedFinetuneNewRoute,
  AuthenticatedModelCardsIdRoute: AuthenticatedModelCardsIdRoute,
  AuthenticatedModelCardsNewRoute: AuthenticatedModelCardsNewRoute,
  AuthenticatedPromptsNewRoute: AuthenticatedPromptsNewRoute,
  AuthenticatedRagIdRoute: AuthenticatedRagIdRoute,
  AuthenticatedRagNewRoute: AuthenticatedRagNewRoute,
  AuthenticatedAuditReportsIndexRoute: AuthenticatedAuditReportsIndexRoute,
  AuthenticatedBenchmarksIndexRoute: AuthenticatedBenchmarksIndexRoute,
  AuthenticatedChunkingIndexRoute: AuthenticatedChunkingIndexRoute,
  AuthenticatedCostsIndexRoute: AuthenticatedCostsIndexRoute,
  AuthenticatedDatasetsIndexRoute: AuthenticatedDatasetsIndexRoute,
  AuthenticatedEmbeddingsIndexRoute: AuthenticatedEmbeddingsIndexRoute,
  AuthenticatedExperimentsIndexRoute: AuthenticatedExperimentsIndexRoute,
  AuthenticatedFinetuneIndexRoute: AuthenticatedFinetuneIndexRoute,
  AuthenticatedModelCardsIndexRoute: AuthenticatedModelCardsIndexRoute,
  AuthenticatedPromptsIndexRoute: AuthenticatedPromptsIndexRoute,
  AuthenticatedRagIndexRoute: AuthenticatedRagIndexRoute,
  AuthenticatedBenchmarksIdIndexRoute: AuthenticatedBenchmarksIdIndexRoute,
  AuthenticatedPromptsIdIndexRoute: AuthenticatedPromptsIdIndexRoute,
  AuthenticatedBenchmarksIdRunsRunIdRoute:
    AuthenticatedBenchmarksIdRunsRunIdRoute,
  AuthenticatedPromptsIdRunsRunIdRoute: AuthenticatedPromptsIdRunsRunIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareBenchmarksTokenRoute: ShareBenchmarksTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
